	
	CREATE TABLE STUDENT(
	STUDENTID INTEGER [NOT NULL],
	STUDENTNAME INTEGER [NOT NULL],
	DEGREEID INTEGER [NOT NULL],
	SUBJECTID INTEGER [NOT NULL]
	CONSTRAINT Student_PK PRIMARY KEY (STUDENTID),
        CONSTRAINT fk_StudentDID FOREIGN KEY (DEGREEID) REFERENCES DEGREE_CLASS(DEGREEID),
	CONSTRAINT fk_StudentSUBID FOREIGN KEY (SUBJECTID) REFERENCES SUBJECT(SUBJECTID),
	);

	CREATE DEGREE_CLASS(
	DEGREEID INTEGER [NOT NULL],
	DEGREECLASS VARCHAR [NOT NULL]
	CONSTRAINT Degree_PK PRIMARY KEY (DEGREEID)
	);
	
	CREATE EXAM(
	EXAMID INTEGER [NOT NULL],
	MODULENUM VARCHAR [NOT NULL],
	SYID INTEGER [NOT NULL]
	CONSTRAINT Exam_PK PRIMARY KEY (EXAMID),
	CONSTRAINT fk_ExamModNum FOREIGN KEY (MODULENUM) REFERENCES MODULE(MODULENUM),
	CONSTRAINT fk_ExamSYID FOREIGN KEY (SYID) REFERENCES SEM_YEAR(SYID)
	);

	CREATE EXAM_DET(
	EXAMID INTEGER [NOT NULL],
	AUTHOR VARCHAR [NOT NULL],
	ATTEMPT INTEGER [NOT NULL],
	WEIGHTING VARCHAR [NOT NULL],
	OUTCOME INTEGER [NOT NULL],
	MARKS INTEGER [NOT NULL],
	QID INTEGER [NOT NULL]
	CONSTRAINT fk_Exam_ID FOREIGN KEY (EXAMID) REFERENCES EXAM(EXAMID),
	CONSTRAINT fk_Exam_QID FOREIGN KEY (QID) REFERENCES EXAM(QID)		
	);

	CREATE SEM_YEAR(
	SYID INTEGER [NOT NULL],
	SEMESTER VARCHAR [NOT NULL],
	YID INTEGER [NOT NULL]
	CONSTRAINT SEM_YEAR_PK PRIMARY KEY (SYID),
	);

	CREATE YEAR(
	YID INTEGER [NOT NULL],
	YEAR VARCHAR [NOT NULL]
        CONSTRAINT SEM_YEAR_PK PRIMARY KEY (YID)
	);

	CREATE SUBJECT(
	SUBJECTID INTEGER [NOT NULL],
	SUBJECTNAME VARCHAR [NOT NULL]
	);	

	CREATE MODULE(
	MODNUM INTEGER [NOT NULL],
	MODNAME VARCHAR [NOT NULL]
	);	

	CREATE COURSEWORK(
	CWID      INTEGER [NOT NULL],
	MODNUM VARCHAR [NOT NULL],
	SYID       INTEGER [NOT NULL],
	LID       INTEGER [NOT NULL]
	);

	CREATE COURSEWORK_MARKS(
	CWID      INTEGER [NOT NULL],
	WEIGHTING VARCHAR [NOT NULL],
	YID       INTEGER [NOT NULL],
	OUTCOME   VARCHAR [NOT NULL]
	);

	CREATE DEPT(
	DID INTEGER [NOT NULL],
	DEPTNAME VARCHAR [NOT NULL]
	);	


	CREATE STAFF(
	STAFFID INTEGER [NOT NULL],
	STAFFNAME VARCHAR [NOT NULL],
	DID INTEGER [NOT NULL]
	);

	CREATE GRADEREPORT(
	STUDENTID INTEGER [NOT NULL],
	SUBJECTID INTEGER [NOT NULL]
	);	

	CREATE SUBINMOD(
	SUBJECTID INTEGER [NOT NULL],
	MODNUM INTEGER [NOT NULL],
	OVERALLMARK INTEGER[NOT NULL]
	);

	CREATE LECTURER(
	LID INTEGER [NOT NULL],
	LNAME INTEGER [NOT NULL],
	MODNUM INTEGER[NOT NULL]
	);	

	CREATE QUESTIONS(
	QID INTEGER [NOT NULL],
	MARKS INTEGER[NOT NULL]
	);
	
		
	

	
